# Generated by Django 4.2.2 on 2024-01-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='highlist',
            new_name='highlighted',
        ),
    ]
